### ISSUE TITLE
[Feature] getAddressBalance rpc method in qtumd

### ISSUE THREAD

**Issue by raineroviir** [qtumproject/qtum#466]
[qtum-insight-api](https://github.com/qtumproject/insight-api) needs the getAddressBalance rpc method to get wallet balances so the api will work properly for balances, transactions and statistics

From my brief google search, bitcoind has this rpc method, so it shouldn't be too hard to add it to qtum.

**Comment by Bushstar** [comment]
That is not a native RPC call in Bitcoin but is added to a bespoke version used in Bitcore, Qtum has such a version available, please compile and use the daemon from the source code below.

https://github.com/qtumproject/qtum-bitcore

**Comment by raineroviir** [comment]
Thank you!

**Comment by raineroviir** [comment]
I'm still getting this error:

```error: [AddressBalanceService] Update Error { RPCError: Method not found
    at Qtum._wrapRPCError (/Users/raineroviir/qtum/src/myNewNode/node_modules/qtumcore-node/lib/services/qtumd.js:548:13)
    at /Users/raineroviir/qtum/src/myNewNode/node_modules/qtumcore-node/lib/services/qtumd.js:1210:30
    at IncomingMessage.<anonymous> (/Users/raineroviir/qtum/src/myNewNode/node_modules/qtumd-rpc/lib/index.js:107:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: -32601 }
```

**Comment by Bushstar** [comment]
Have you tried running getaddressbalance directly on the daemon to make sure that the call is present?

Also make sure that your conf has the following, if not then start the daemon with reindex.

txindex=1
addressindex=1
timestampindex=1
spentindex=1
addrindex=1

**Comment by changshoumeng** [comment]
yes 
I had the problem,too
I slove it by  build  https://github.com/qtumproject/qtum-bitcore ,and get that 

xxxxx/qtumcorebuild/qtum-bitcore/src/qtumd


http://10.10.29.15:3001/qtum-insight-api/block/48a5a694acb7de232b789cfa5464080554584efb149283fc327bd95cd8bba153


`{
"hash": "48a5a694acb7de232b789cfa5464080554584efb149283fc327bd95cd8bba153",
"size": 327,
"height": 2,
"version": 536870912,
"merkleroot": "fa44c823251b14ff72d95b84bf82f22c8dbbd54501e801ad91497c33532eb303",
"tx": [
"fa44c823251b14ff72d95b84bf82f22c8dbbd54501e801ad91497c33532eb303"
],
"time": 1524840599,
"nonce": 3,
"bits": "207fffff",
"difficulty": 0,
"chainwork": "0000000000000000000000000000000000000000000000000000000000000006",
"confirmations": 4400,
"previousblockhash": "1237e87ec56b93e62339651f0b68df23f044be0cf811fe80e3728e427584d232",
"nextblockhash": "1f07e9757d09f2872b20b245a9271c87f7651e245dc091494fba59976db7c8e0",
"flags": "proof-of-work",
"reward": 20000,
"isMainChain": true,
"minedBy": "qWHGS5rqpXqy6Bgt9aesVqTg9ta47sdhXb",
"poolInfo": {}
}`
