### ISSUE TITLE
Return revert messages in callcontract and gettransactionreceipt

### ISSUE THREAD

**Issue by hayeah** [qtumproject/qtum#701]
Popular Solidity contract lib now generally have revert messages builtin to aid debugging, but is no way to get the revert message of a contract method call in QTUM.

Example see: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/d9d1082247fe90b878fb5e517829fcd129a6ca7a/contracts/crowdsale/Crowdsale.sol#L57-L59

# current behavour

The only indication of failure for the `callcontract` RPC call is currently "excepted: BadInstruction" for tx or call that would revert. 

* Should return "excepted: Reverted"
* Should return revert message.

```
{
  "error": null,
  "id": "178",
  "result": {
    "address": "ef581a96579e8eb7415dd1e4858cb0a04a6d5473",
    "executionResult": {
      "codeDeposit": 0,
      "depositSize": 0,
      "excepted": "BadInstruction",
      "gasForDeposit": 0,
      "gasRefunded": 0,
      "gasUsed": 6721975,
      "newAddress": "ef581a96579e8eb7415dd1e4858cb0a04a6d5473",
      "output": ""
    },
    "transactionReceipt": {
      "bloom": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000",
      "gasUsed": 6721975,
      "log": [],
      "stateRoot": "b3ae15fdffc3c2aa53fb42eab82cdb88d0d443a55a4169176df85228dca7fd18"
    }
  }
}

```

## expected behaviour

The RPC call should return the revert message. The Ethereum `eth_call` returns a 'message':

```
{
  "id": 1,
  "jsonrpc": "2.0",
  "error": {
    "message": "VM Exception while processing transaction: revert CapperRole: caller does not have the Capper role",
    "code": -32000,
    "data": {
      "0x90f48d0a98bf9e18bba07a9538da7a1c21fcccab4aaca3afd60b6d0677098117": {
        "error": "revert",
        "program_counter": 621,
        "return": "0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000030436170706572526f6c653a2063616c6c657220646f6573206e6f742068617665207468652043617070657220726f6c6500000000000000000000000000000000",
        "reason": "CapperRole: caller does not have the Capper role"
      },
      "stack": "o: VM Exception while processing transaction: revert CapperRole: caller does not have the Capper role\n    at Function.o.fromResults (/Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:10:81931)\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:47:121235\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1853218\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26124\n    at i (/Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:41179)\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1210468\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:105466\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:32:392\n    at c (/Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:32:5407)\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:32:317\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1871644\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:23237\n    at o (/Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26646)\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26124\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1864681\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1862544\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:61:1889757\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:23237\n    at o (/Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26646)\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:26124\n    at /Users/howard/src/openzeppelin-solidity/node_modules/ganache-cli/build/ganache-core.node.cli.js:2:5439\n    at FSReqCallback.args [as oncomplete] (fs.js:145:20)",
      "name": "o"
    }
  }
}
```

I am not sure if the error prefix `VM Exception while processing transaction` used by ETH RPC is useful for QTUM. As we already use 'excepted' to indicate different exception types (e.g. out of gas, revert, bad instruction).

My proposal is maybe to add a `revertMessage` filed, specifically for reverted transactions.

- [ ] For reverted tx, the "excepted" result should be "REVERTED", not "BADINSTRUCTION"
- [ ] Return revert message for callcontract if there is one.
- [ ] Return revert message for gettransactionreceipt if there is one.
- [ ] For callcontract, the 'gasrefund' calculation shouldn't consume 100% of the gas...?

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/pull/709
